
version: '3'

services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile8
    image: my-laravel-app
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    networks:
      - app-network

  # MySQL Service
  # database:
  #   image: mysql:5.7.22
  #   container_name: database
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "4306:3306"
  #   environment:
  #     MYSQL_DATABASE: laravel
  #     MYSQL_ROOT_PASSWORD: root_password
  #     MYSQL_PASSWORD: password
  #     MYSQL_USER: user
  #   networks:
  #     - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network

# Networks Configuration
networks:
  app-network:
    driver: bridge
 